name: .NET-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build ./Src/Denovo.sln -c Release
    - name: Test
      run: dotnet test ./Src/Tests/Tests.csproj --no-build --verbosity normal -c Release
